export const getFieldConfigDefaults = (fieldType: string): any => {
    const configs: Record<string, any> = {
      text: { subtype: "short" },
      text_with_icon: { subtype: "short", icon_options: [] },
      select: { options: [], allow_multiple: false },
      searchable: { options: [] },
      select_with_icons: { options: [], allow_multiple: false, icons_url: [] },
      select_background: {
        options: [],
        allow_multiple: false,
        backgrounds_url: [],
      },
      date: { date_format: "DD/MM/YYYY" },
      date_range: {
        date_format: "DD/MM/YYYY",
        start_date_label: "Fecha inicio",
        start_date_description: "Seleccione la fecha de inicio",
        end_date_label: "Fecha fin",
        end_date_description: "Seleccione la fecha de fin",
      },
      image_upload: {
        max_file_size: "5MB",
        allowed_formats: ["jpg", "jpeg", "png"],
      },
      list: {
        max_items: 10,
        min_items: 1,
        item_schema: {
          item_name: {
            field_id: "item_name",
            display_name: "Nombre del elemento",
            type: "text",
            form: true,
            bulletin: true,
          },
          item_description: {
            field_id: "item_description",
            display_name: "Descripción",
            type: "text",
            form: true,
            bulletin: false,
          },
        },
      },
      climate_data_puntual: { available_parameters: {} },
      algorithm: { options: [] },
      page_number: { format: "Página {page} de {total}", is_autogenerated: true },
      card: { available_cards: [] },
      image: { images: [] },
    };
  
    return configs[fieldType] || {};
  };
