// Tipos para la creación y manejo de plantillas basados en la documentación MongoDB

import {
  LogObject,
  AccessConfig,
  StyleConfig,
  ValidationRules,
  TemplateStatus,
} from "./core";

// Tipos de campo específicos para field_config
export interface TextFieldConfig {
  subtype?: "short" | "long";
}

export interface TextWithIconFieldConfig {
  subtype?: "short" | "long";
  icon_options: string[]; // URLs de los iconos que se pueden seleccionar
  selected_icon?: string; // URL del icono seleccionado cuando form es false
  showLabel?: boolean; // Si true, muestra el label al lado del valor en el preview; si false, solo muestra el valor
}

export interface ClimateDataFieldConfig {
  available_parameters: Record<
    string,
    {
      label: string;
      unit: string;
      type: "number" | "text";
      col_name: string;
      showName?: boolean; // Si true, muestra el nombre del parámetro; si false, solo muestra valor y unidad
      style_config?: StyleConfig; // Estilos individuales para este parámetro
    }
  >;
}

export interface ListFieldConfig {
  max_items_per_page?: number;
  max_items: number;
  min_items: number;
  item_schema: Record<string, FieldBase>;
}

export interface SelectFieldConfig {
  options: string[];
  allow_multiple?: boolean;
}

export interface SearchableFieldConfig {
  options: string[]; // Opciones predefinidas disponibles para seleccionar
}

export interface SelectWithIconsFieldConfig extends SelectFieldConfig {
  icons_url: string[];
  show_label?: boolean; // Si se muestra el label al lado del icono
}

export interface SelectBackgroundFieldConfig extends SelectFieldConfig {
  backgrounds_url: string[];
}

export interface DateFieldConfig {
  date_format?: string;
  text_decoration?: {
    prefix?: string;
    suffix?: string;
  };
}

export interface DateRangeFieldConfig {
  date_format?: string;
  start_date_label: string;
  start_date_description: string;
  end_date_label: string;
  end_date_description: string;
  show_moon_phases?: boolean; // Si se muestran las fases de la luna
  start_moon_phase?: "llena" | "nueva" | "cuartoCreciente" | "cuartoMenguante"; // Fase de la luna para fecha inicio
  end_moon_phase?: "llena" | "nueva" | "cuartoCreciente" | "cuartoMenguante"; // Fase de la luna para fecha fin
}

export interface ImageUploadFieldConfig {
  max_file_size: string;
  allowed_formats: string[];
  max_width?: number;
  max_height?: number;
}

export interface AlgorithmFieldConfig {
  options: string[]; // Array de algoritmos disponibles
}

export interface PageNumberFieldConfig {
  format: string; // Ej: "Página {page} de {total}"
  is_autogenerated?: boolean;
}

export interface CardFieldConfig {
  card_type?: string; // Tipo de card (opcional para filtrar por tipo)
  available_cards: string[]; // Array de IDs de cards que el usuario puede seleccionar
}

export interface MoonCalendarFieldConfig {
  title_icon?: string; // URL del icono que acompaña el título
  title_label?: string; // Label del título con {month} como placeholder para el mes
}

export interface ImageFieldConfig {
  images: string[];
  show_label?: boolean; // Si se muestra el label debajo de la imagen
  label_text?: string; // Texto del label que se muestra debajo de la imagen
}

// Tipo base para todos los campos
export interface FieldBase {
  field_id: string;
  display_name: string;
  type:
    | "text"
    | "text_with_icon"
    | "climate_data_puntual"
    | "list"
    | "select"
    | "searchable"
    | "select_with_icons"
    | "select_background"
    | "number"
    | "date"
    | "date_range"
    | "image_upload"
    | "algorithm"
    | "page_number"
    | "card"
    | "image"
    | "moon_calendar";
  description?: string;
  label?: string;
  form: boolean;
  bulletin: boolean;
  style_config?: StyleConfig;
  style_manually_edited?: boolean; // Flag para indicar si los estilos han sido editados manualmente
  validation?: ValidationRules;
  field_config?:
    | TextFieldConfig
    | TextWithIconFieldConfig
    | ClimateDataFieldConfig
    | ListFieldConfig
    | SelectFieldConfig
    | SearchableFieldConfig
    | SelectWithIconsFieldConfig
    | SelectBackgroundFieldConfig
    | DateFieldConfig
    | DateRangeFieldConfig
    | ImageUploadFieldConfig
    | AlgorithmFieldConfig
    | PageNumberFieldConfig
    | CardFieldConfig
    | ImageFieldConfig
    | MoonCalendarFieldConfig;
  value?:
    | string
    | number
    | boolean
    | Date
    | string[]
    | Record<string, any>[]
    | null
    | undefined; // Para campos con valores predefinidos
}

// Tipos específicos de campo (para type safety)
export interface TextField extends FieldBase {
  type: "text";
  field_config?: TextFieldConfig;
}

export interface TextWithIconField extends FieldBase {
  type: "text_with_icon";
  field_config: TextWithIconFieldConfig;
}

export interface ClimateDataField extends FieldBase {
  type: "climate_data_puntual";
  field_config: ClimateDataFieldConfig;
}

export interface ListField extends FieldBase {
  type: "list";
  field_config: ListFieldConfig;
}

export interface SelectField extends FieldBase {
  type: "select";
  field_config: SelectFieldConfig;
}

export interface SearchableField extends FieldBase {
  type: "searchable";
  field_config: SearchableFieldConfig;
}

export interface SelectWithIconsField extends FieldBase {
  type: "select_with_icons";
  field_config: SelectWithIconsFieldConfig;
}

export interface SelectBackgroundField extends FieldBase {
  type: "select_background";
  field_config: SelectBackgroundFieldConfig;
}

export interface NumberField extends FieldBase {
  type: "number";
}

export interface DateField extends FieldBase {
  type: "date";
  field_config?: DateFieldConfig;
}

export interface DateRangeField extends FieldBase {
  type: "date_range";
  field_config: DateRangeFieldConfig;
}

export interface ImageUploadField extends FieldBase {
  type: "image_upload";
  field_config: ImageUploadFieldConfig;
}

export interface AlgorithmField extends FieldBase {
  type: "algorithm";
  field_config: AlgorithmFieldConfig;
}

export interface PageNumberField extends FieldBase {
  type: "page_number";
  field_config: PageNumberFieldConfig;
}

export interface CardField extends FieldBase {
  type: "card";
  field_config: CardFieldConfig;
}

export interface ImageField extends FieldBase {
  type: "image";
  field_config: ImageFieldConfig;
}

export interface MoonCalendarField extends FieldBase {
  type: "moon_calendar";
  field_config?: MoonCalendarFieldConfig;
}

// Union type para todos los tipos de campo
export type Field =
  | TextField
  | TextWithIconField
  | ClimateDataField
  | ListField
  | SelectField
  | SearchableField
  | SelectWithIconsField
  | SelectBackgroundField
  | NumberField
  | DateField
  | DateRangeField
  | ImageUploadField
  | AlgorithmField
  | PageNumberField
  | CardField
  | ImageField
  | MoonCalendarField;

export interface Block {
  block_id: string;
  display_name: string;
  icon_url?: string;
  style_config?: StyleConfig;
  fields: Field[];
}

export interface HeaderFooterConfig {
  style_config?: StyleConfig;
  fields: Field[];
}

export interface Section {
  section_id: string;
  display_name: string;
  background_url: string[];
  order: number;
  style_config?: StyleConfig;
  icon_url: string;
  header_config?: HeaderFooterConfig; // Header específico de la sección
  footer_config?: HeaderFooterConfig; // Footer específico de la sección
  blocks: Block[];
}

export interface TemplateVersionContent {
  style_config?: StyleConfig;
  header_config?: HeaderFooterConfig; // Header global
  sections: Section[];
  footer_config?: HeaderFooterConfig; // Footer global
}

export interface TemplateVersion {
  _id?: string;
  template_master_id?: string;
  version_num?: number;
  previous_version_id?: string | null;
  log: LogObject;
  commit_message: string;
  content: TemplateVersionContent;
}

export interface TemplateMaster {
  _id?: string;
  template_name: string;
  name_machine: string; // Identificador único en formato slug (ej: "monthly-climate-bulletin")
  description: string;
  log: LogObject;
  status: TemplateStatus;
  current_version_id?: string;
  access_config: AccessConfig;
  thumbnail_images?: string[]; // Rutas a las imágenes de preview de las secciones (máximo 3)
  section_count?: number; // Número total de secciones del template
}

// Tipos para el formulario de creación
export interface CreateTemplateData {
  master: Omit<TemplateMaster, "_id" | "current_version_id">;
  version: Omit<
    TemplateVersion,
    "_id" | "template_master_id" | "previous_version_id"
  >;
}

// Tipos para los pasos del wizard
export type TemplateCreationStep =
  | "basic-info"
  | "general-config"
  | "header-footer"
  | "sections";

export interface TemplateCreationState {
  currentStep: TemplateCreationStep;
  data: CreateTemplateData;
  errors: Record<string, string[]>;
  isValid: boolean;
}

// Constantes para los tipos de campo disponibles
export const FIELD_TYPES = [
  "text",
  "text_with_icon",
  "climate_data_puntual",
  "list",
  "select",
  "searchable",
  "select_with_icons",
  "select_background",
  "number",
  "date",
  "date_range",
  "image_upload",
  "algorithm",
  "page_number",
  "card",
  "image",
  "moon_calendar",
] as const;

// Constantes específicas para template creation
export const TEXT_SUBTYPES = ["short", "long"] as const;

export type FieldType = (typeof FIELD_TYPES)[number];
export type TextSubtype = (typeof TEXT_SUBTYPES)[number];

// Tipo para la respuesta de la API del endpoint /templates/{id}/current-version
export interface TemplateWithCurrentVersion {
  master: TemplateMaster;
  current_version: TemplateVersion;
}
