// Tipos para la creación y manejo de plantillas basados en la documentación MongoDB

import {
  LogObject,
  AccessConfig,
  StyleConfig,
  ValidationRules,
  TemplateStatus,
} from "./core";

// Tipos de campo específicos para field_config
export interface TextFieldConfig {
  subtype?: "short" | "long";
}

export interface ClimateDataFieldConfig {
  available_parameters: Record<
    string,
    {
      label: string;
      unit: string;
      type: "number" | "text";
      col_name: string;
    }
  >;
}

export interface ListFieldConfig {
  max_items_per_page?: number;
  max_items: number;
  min_items: number;
  item_schema: Record<string, FieldBase>;
}

export interface SelectFieldConfig {
  options: string[];
  allow_multiple?: boolean;
}

export interface SelectWithIconsFieldConfig extends SelectFieldConfig {
  icons_url: string[];
}

export interface SelectBackgroundFieldConfig extends SelectFieldConfig {
  backgrounds_url: string[];
}

export interface DateFieldConfig {
  date_format?: string;
  text_decoration?: {
    prefix?: string;
    suffix?: string;
  };
}

export interface DateRangeFieldConfig {
  date_format?: string;
  start_date_label: string;
  start_date_description: string;
  end_date_label: string;
  end_date_description: string;
}

export interface ImageUploadFieldConfig {
  max_file_size: string;
  allowed_formats: string[];
  max_width?: number;
  max_height?: number;
}

export interface AlgorithmFieldConfig {
  options: string[]; // Array de algoritmos disponibles
}

export interface PageNumberFieldConfig {
  format: string; // Ej: "Página {page} de {total}"
  is_autogenerated?: boolean;
}

export interface CardFieldConfig {
  card_type: string; // Ej: "pest_or_disease", "crop_info"
}

export interface BackgroundUrlFieldConfig {
  background_url: string;
}

// Tipo base para todos los campos
export interface FieldBase {
  field_id: string;
  display_name: string;
  type:
    | "text"
    | "climate_data_puntual"
    | "list"
    | "select"
    | "select_with_icons"
    | "select_background"
    | "number"
    | "date"
    | "date_range"
    | "image_upload"
    | "algorithm"
    | "page_number"
    | "card"
    | "background_url";
  description?: string;
  label?: string;
  form: boolean;
  bulletin: boolean;
  style_config?: StyleConfig;
  style_manually_edited?: boolean; // Flag para indicar si los estilos han sido editados manualmente
  validation?: ValidationRules;
  field_config?:
    | TextFieldConfig
    | ClimateDataFieldConfig
    | ListFieldConfig
    | SelectFieldConfig
    | SelectWithIconsFieldConfig
    | SelectBackgroundFieldConfig
    | DateFieldConfig
    | DateRangeFieldConfig
    | ImageUploadFieldConfig
    | AlgorithmFieldConfig
    | PageNumberFieldConfig
    | CardFieldConfig
    | BackgroundUrlFieldConfig;
  value?: string | number | boolean | Date | string[] | null | undefined; // Para campos con valores predefinidos
}

// Tipos específicos de campo (para type safety)
export interface TextField extends FieldBase {
  type: "text";
  field_config?: TextFieldConfig;
}

export interface ClimateDataField extends FieldBase {
  type: "climate_data_puntual";
  field_config: ClimateDataFieldConfig;
}

export interface ListField extends FieldBase {
  type: "list";
  field_config: ListFieldConfig;
}

export interface SelectField extends FieldBase {
  type: "select";
  field_config: SelectFieldConfig;
}

export interface SelectWithIconsField extends FieldBase {
  type: "select_with_icons";
  field_config: SelectWithIconsFieldConfig;
}

export interface SelectBackgroundField extends FieldBase {
  type: "select_background";
  field_config: SelectBackgroundFieldConfig;
}

export interface NumberField extends FieldBase {
  type: "number";
}

export interface DateField extends FieldBase {
  type: "date";
  field_config?: DateFieldConfig;
}

export interface DateRangeField extends FieldBase {
  type: "date_range";
  field_config: DateRangeFieldConfig;
}

export interface ImageUploadField extends FieldBase {
  type: "image_upload";
  field_config: ImageUploadFieldConfig;
}

export interface AlgorithmField extends FieldBase {
  type: "algorithm";
  field_config: AlgorithmFieldConfig;
}

export interface PageNumberField extends FieldBase {
  type: "page_number";
  field_config: PageNumberFieldConfig;
}

export interface CardField extends FieldBase {
  type: "card";
  field_config: CardFieldConfig;
}

export interface BackgroundUrlField extends FieldBase {
  type: "background_url";
  field_config: BackgroundUrlFieldConfig;
}

// Union type para todos los tipos de campo
export type Field =
  | TextField
  | ClimateDataField
  | ListField
  | SelectField
  | SelectWithIconsField
  | SelectBackgroundField
  | NumberField
  | DateField
  | DateRangeField
  | ImageUploadField
  | AlgorithmField
  | PageNumberField
  | CardField
  | BackgroundUrlField;

export interface Block {
  block_id: string;
  display_name: string;
  icon_url?: string;
  fields: Field[];
}

export interface HeaderFooterConfig {
  style_config?: StyleConfig;
  fields: Field[];
}

export interface Section {
  section_id: string;
  display_name: string;
  background_url: string[];
  order: number;
  style_config?: StyleConfig;
  icon_url: string;
  header_config?: HeaderFooterConfig; // Header específico de la sección
  blocks: Block[];
}

export interface TemplateVersionContent {
  style_config?: StyleConfig;
  header_config?: HeaderFooterConfig; // Header global
  sections: Section[];
  footer_config?: HeaderFooterConfig; // Footer global
}

export interface TemplateVersion {
  _id?: string;
  template_master_id?: string;
  version_num: number;
  previous_version_id?: string | null;
  log: LogObject;
  commit_message: string;
  content: TemplateVersionContent;
}

export interface TemplateMaster {
  _id?: string;
  template_name: string;
  description: string;
  log: LogObject;
  status: TemplateStatus;
  current_version_id?: string;
  access_config: AccessConfig;
}

// Tipos para el formulario de creación
export interface CreateTemplateData {
  master: Omit<TemplateMaster, "_id" | "current_version_id">;
  version: Omit<
    TemplateVersion,
    "_id" | "template_master_id" | "previous_version_id"
  >;
}

// Tipos para los pasos del wizard
export type TemplateCreationStep =
  | "basic-info"
  | "general-config"
  | "header-footer"
  | "sections";

export interface TemplateCreationState {
  currentStep: TemplateCreationStep;
  data: CreateTemplateData;
  errors: Record<string, string[]>;
  isValid: boolean;
}

// Constantes para los tipos de campo disponibles
export const FIELD_TYPES = [
  "text",
  "climate_data_puntual",
  "list",
  "select",
  "select_with_icons",
  "select_background",
  "number",
  "date",
  "date_range",
  "image_upload",
  "algorithm",
  "page_number",
  "card",
  "background_url",
] as const;

// Constantes específicas para template creation
export const TEXT_SUBTYPES = ["short", "long"] as const;

export type FieldType = (typeof FIELD_TYPES)[number];
export type TextSubtype = (typeof TEXT_SUBTYPES)[number];
